theme: jekyll-theme-slate
title: Social Media Project
description: This site is for IDT510 - Social Media. Being a summary of the social media platforms we've evaluated and compared throughout the course. 
