theme: jekyll-theme-slate
title: Social Media Project
description: by Jay Pestillo

header_pages:
  - index.md
  - traditional_media.md
  - microblogging.md
  - spotify_twitter.md
  - pinterest.md
  - linkedin.md
  - social_gaming.md